[target.wasm32-wasip1]
rustflags = [
    "-C",
    "opt-level=z",
    "-C",
    "lto=yes",
    "-C",
    "codegen-units=1",
    "-C",
    "panic=abort",
    "-C",
    "debuginfo=0",
    "-C",
    "strip=symbols",
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=--strip-all",
]
